#!/command/with-contenv bash

set -e

echo "Starting openclaw..."

config_file="$HOME/.openclaw/openclaw.json"
if [ ! -f "$config_file" ]; then
	echo "openclaw config not found; writing default to ${config_file}"
	mkdir -p "$(dirname "${config_file}")"
    cp $HOME/default-config/openclaw.json "${config_file}"

    openclaw config set gateway.mode "${OPENCLAW_GATEWAY_MODE:-local}"
    openclaw config set gateway.controlUi.allowInsecureAuth "${OPENCLAW_GATEWAY_ALLOW_INSECURE_AUTH:-false}"
    openclaw config set gateway.controlUi.dangerouslyDisableDeviceAuth "${OPENCLAW_GATEWAY_DANGEROUSLY_DISABLE_DEVICE_AUTH:-false}"
    orig="${OPENCLAW_GATEWAY_ALLOWED_ORIGINS:-http://localhost:18789}"
    escaped=$(printf '%s' "$orig" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
    replaced=$(printf '%s' "$escaped" | sed -e 's/,/\",\"/g')
    json="[\"$replaced\"]"
    openclaw config set gateway.controlUi.allowedOrigins "$json"
fi

exec openclaw gateway \
        --bind "${OPENCLAW_GATEWAY_BIND:-lan}" \
        --port "${OPENCLAW_GATEWAY_PORT:-18789}" \
        --token "${OPENCLAW_GATEWAY_TOKEN:-123456}" \
        --verbose
